[package]
name = "outliner"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
hifitime = "4.2.1"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
rusqlite = "0.37.0"
thiserror = "2.0.16"
uuid = { version = "1.18.1", features = ["v4"] }
